### ISSUE TITLE
AWS Karpenter support

### ISSUE THREAD

**Issue by nuwang** [aws-samples/aws-eks-accelerator-for-terraform#132]
Hi,

Are there any plans to include [AWS Karpenter](https://karpenter.sh/docs/getting-started-with-terraform/) as an alternative to the cluster autoscaler?

**Comment by vara-bonthu** [comment]
@nuwang Thanks for your interest. Yes, we are working on it now. It will be added soon with some examples

**Comment by vara-bonthu** [comment]
Closing the issue with the Feature merge
