### ISSUE TITLE
Feature: Multi-tenant (Ingress per tenant)

### ISSUE THREAD

**Issue by sharepointoscar** [aws-samples/aws-eks-accelerator-for-terraform#15]
Since the awesome accelerator already supports multi-tenant scenarios, it would be great to also allow a tenant to have a dedicated ingress, like NGNIX.

The controller would include the corresponding cert, DNS etc.

**Example**
Finance namespaces can have one Ingress Controller and Marketing division can have their own Ingress Controller. 

This would also translate into cost savings on our implementations.

**Comment by askulkarni2** [comment]
Close issue here as we track this internally.
