### ISSUE TITLE
Feature request: Pass workers_additional_policies to nodes

### ISSUE THREAD

**Issue by schwichti** [aws-samples/aws-eks-accelerator-for-terraform#175]
Hi,

I want to pass additional policies to EKS nodes / workers. The EKS accelerator uses the EKS module under the hood which has the `workers_additional_policies argument` for that. However, the argument is not exposed by the accelerator. 

Is there a workaround for this? I want to use the accelerator as a module. One solution might be to get the IAM role for the EKS nodes from the accelerator and attach a policy via the `aws_iam_role_policy_attachment` resouce from the aws provider. However, I do not see how I can get the IAM role from the accelerator.

**Comment by vara-bonthu** [comment]
Thank for raising this @schwichti issue. Yes, currently we are not supporting sending additional IAM policies to the Node groups. I believe this is useful feature and it can be easily added to our module. I will add this task to our ROADMAP and keep you informed soon. 

On another note we recommend using IRSA instead of adding more policies to the Worker Nodes itself. This narrows the security to the specific Pods instead of nodes

**Comment by schwichti** [comment]
Thanks, the IRSA approach is even better, although I have to rework the k8s resources.

One question regarding this: do you recommend having dedicated service accounts per pod with least priviledges? 
From a security perspective this seems reasonable. But managing all the service accounts might getting complex (I have 70 pods). I am also in the process to integrate AWS secrets manager to store k8s secrets and the secret store driver also makes use of IRSA.

Do be more precise: I wonder if it is practical to create an own service account per pod that has the priviledges of the default SA per default. If a pod needs more priviledges, the roles can be simply added to their SA. This approach seems to give more security, is flexible, and the managing overhead seems ok.

**Comment by schwichti** [comment]
Maybe I have found another use case for exposing `workers_additional_policies`: add the AmazonSSMManagedInstanceCore policy to nodes to connect to them via AWS Session Manager.

**Comment by schwichti** [comment]
I just found out that `workers_additional_policies` have been removed in the eks module version 18.

**Comment by vara-bonthu** [comment]
I have included this policy `AmazonSSMManagedInstanceCore` to node groups in my new [PR](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/179).
