### ISSUE TITLE
k8s_labels for self managed node group doesn't work

### ISSUE THREAD

**Issue by spy1233** [aws-samples/aws-eks-accelerator-for-terraform#185]
Hi, 
It seems k8s_labels for self managed node group doesn't work.
I tried it with [this example](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples/1-eks-cluster-with-new-vpc).
Thanks.

**Comment by vara-bonthu** [comment]
Thanks for raising this issue. Yes, `k8s_labels` and `k8s_taints` are supported only by using **Managed Node groups** but not with **Self-managed node groups** using this module. 
I will will raise a PR and update the docs
