### ISSUE TITLE
Terraform plan

### ISSUE THREAD

**Issue by skuriyadi** [aws-samples/aws-eks-accelerator-for-terraform#196]
Hi Team,

I am trying to create a cluster with managed node group with a main.tf, variable.tf and tfvars file but the terraform plan is taking more than 15 minutes to execute. Please let me know if there something which I am doing wrong/different. 

I am using https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/examples/1-eks-cluster-with-new vpc/main.tf example.

Thank you

**Comment by rl-abdulkarim** [comment]
Would be nice if you could share the exact command that you ran and the output that you saw at the end of 15 minutes.

Usually plan shouldn't take that long, the apply command takes 15 minutes or more because AWS requires 10+ minutes to provision EKS cluster itself.

**Comment by skuriyadi** [comment]
I used the terraform plan and I used  https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/examples/1-eks-cluster-with-new and the plan ran successfully.

**Comment by rl-abdulkarim** [comment]
I tried running terraform plan on main branch and it takes under 2 minutes for plan to complete. 

```
~/aws-eks-accelerator-for-terraform/e/1-eks-cluster-with-new-vpc 
❯ time terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_eks_cluster.cluster will be read during apply
  # (config refers to values not yet known)
...
...
...
Plan: 75 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply"
now.
terraform plan  159.07s user 6.03s system 148% cpu 1:51.25 total
```


Are you on a slow internet connection by any chance?

**Comment by skuriyadi** [comment]
I am running a 300 mpbs connection. Can you please paste the source url here, I am using  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform"

**Comment by rl-abdulkarim** [comment]
I haven't made any modifications, all I did was 

1. `git clone git@github.com:aws-samples/aws-eks-accelerator-for-terraform.git `
2. `cd examples/1-eks-cluster-with-new-vpc`
3. `terraform plan`

**Comment by skuriyadi** [comment]
I am trying to source the modules from the git repo instead of cloning and using it.

**Comment by skuriyadi** [comment]
Thank you @vara-bonthu , I am using` depends_on` and also creating eks cluster and creating the kubernetes components in same terraform apply. I will decouple eks creation and kubernetes components.
