### ISSUE TITLE
Documentation: Add example for ArgoCD way of managing add-ons

### ISSUE THREAD

**Issue by rl-abdulkarim** [aws-samples/aws-eks-accelerator-for-terraform#197]
As per the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/add-ons/index.md#gitops-with-argocd) there are 2 ways to manage addons

1. Via Terraform by leveraging the Terraform Helm provider.
2. Via GitOps with ArgoCD.

The examples/ directory has examples that make use of Terraform Helm provider. It would be great to have a working example with ArgoCD method as well.

**Comment by vara-bonthu** [comment]
Hi @rl-abdulkarim Thanks for raising this question. We have an active [PR](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/191) that should address your query. This new example is going to show how you can manage add-ons using ArgoCD.

**Comment by rl-abdulkarim** [comment]
That's awesome!

Should I close this issue now or will it auto-close with the PR? :)

**Comment by kcoleman731** [comment]
@rl-abdulkarim ArgoCD example has been merged. Feel free to check it out here https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples/6-eks-cluster-with-argocd
