### ISSUE TITLE
Cluster name

### ISSUE THREAD

**Issue by skuriyadi** [aws-samples/aws-eks-accelerator-for-terraform#199]
Hi Team,

Is there any option to pass cluster name instead of tenant, environment and zone separately. I see that cluster name is derived from eks_tags module. Is it possible to add an option to pass just the cluster name if the eks_tags values are not provided.

**Comment by vara-bonthu** [comment]
Yes, It's currently not supported as we derive the cluster name using the tags. However, we will add your request as an enhancement to allow users to pass the cluster_name.

**Comment by skuriyadi** [comment]
Thank you @vara-bonthu

**Comment by schwichti** [comment]
I would appreciate this feature.
