### ISSUE TITLE
documentation for k8s_taints

### ISSUE THREAD

**Issue by schwichti** [aws-samples/aws-eks-accelerator-for-terraform#205]
`k8s_taints` are not documented right now. 
see https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/modules/aws-eks-managed-node-groups/locals.tf#L24

Here is a working example you can use:
```terraform
k8s_taints = [{key= "purpose", value="execution", "effect"="NO_SCHEDULE"}]
```

I haven't tested it with fargate profiles:
https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/479b1a909c07fdc072181056bdcb799d90d8a877/modules/aws-eks-fargate-profiles/locals.tf#L8

**Comment by vara-bonthu** [comment]
@schwichti Thanks for testing and providing inputs. This looks good for me. 
I am happy for you to raise a PR and show this as an example for the link you mentioned above

**Comment by vara-bonthu** [comment]
Closing the issue since the PR is merged now
