### ISSUE TITLE
KMS Key

### ISSUE THREAD

**Issue by skuriyadi** [aws-samples/aws-eks-accelerator-for-terraform#209]
Hi Team,

Is there an option to change/update deletion_window_in_days for KMS key.

**Comment by vara-bonthu** [comment]
Hi @skuriyadi KMS Key deletion window is currently set to default value of 30 days. Currently this parameter is not exposed to change modify the value. May be we can look at the option to allow users to pass their own KMS key for EKS Cluster. Raise this as a Feature request. We will add it to backlog. Thanks
