### ISSUE TITLE
[Bug]: Issue with Karpenter example

### ISSUE THREAD

**Issue by ibuchh** [aws-samples/aws-eks-accelerator-for-terraform#229]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

8

### What is your environment, configuration and the example used?

│ Error: Invalid value for module argument
│
│   on main.tf line 135, in module "karpenter-launch-templates":
│  135:   launch_template_config = {
│  136:     linux = {
│  137:       ami                    = "ami-0adc757be1e4e11a1"
│  138:       launch_template_prefix = "karpenter"
│  139:       iam_instance_profile   = module.aws-eks-accelerator-for-terraform.self_managed_node_group_iam_instance_profile_id[0]
│  140:       vpc_security_group_ids = module.aws-eks-accelerator-for-terraform.worker_security_group_id
│  141:       block_device_mappings = [
│  142:         {
│  143:           device_name = "/dev/xvda"
│  144:           volume_type = "gp2"
│  145:           volume_size = "200"
│  146:         }
│  147:       ]
│  148:     },
│  149:     bottlerocket = {
│  150:       ami                    = "ami-03909df9bfcc1e215"
│  151:       launch_template_os     = "bottlerocket"
│  152:       launch_template_prefix = "bottle"
│  153:       iam_instance_profile   = module.aws-eks-accelerator-for-terraform.self_managed_node_group_iam_instance_profile_id[0]
│  154:       vpc_security_group_ids = module.aws-eks-accelerator-for-terraform.worker_security_group_id
│  155:       block_device_mappings = [
│  156:         {
│  157:           device_name = "/dev/xvda"
│  158:           volume_type = "gp2"
│  159:           volume_size = "200"
│  160:         }
│  161:       ]
│  162:     },
│  163:   }
│
│ The given value is not suitable for child module variable "launch_template_config" defined at ../../modules/launch-templates/variables.tf:1,1-34: element "linux":
│ attribute "vpc_security_group_ids": list of string required.

### What did you do and What did you see instead?

Deployment Steps
Step1: Clone the repo using the command below

git clone https://github.com/aws-samples/aws-eks-accelerator-for-terraform.git

Step2: Run Terraform INIT

to initialize a working directory with configuration files

cd examples/eks-cluster-with-karpenter/
terraform init

Step3: Run Terraform PLAN

to verify the resources created by this execution

export AWS_REGION=<ENTER-YOUR-REGION>   # Select your own region
terraform plan

**Comment by vara-bonthu** [comment]
Thanks for raising the issue @ibuchh . I have just raise a PR to fix this example
