### ISSUE TITLE
[Bug]: Running eks-cluster-with-argocd example, causes a crash with unsupported attribute

### ISSUE THREAD

**Issue by ZoesDev** [aws-samples/aws-eks-accelerator-for-terraform#235]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

3.2.2

### What is your environment, configuration and the example used?

Terraform version - 1.0.5 

example used - https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples/eks-cluster-with-argocd with no changes.

### What did you do and What did you see instead?

I ran the normal `terraform init` and `terraform plan` during the plan stage, I get 

```
~/Documents/Customers/lab/eks/aws-eks-accelerator-for-terraform-3.2.2/examples/eks-cluster-with-argocd > terraform plan
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-west-2

╷
│ Error: Unsupported attribute
│ 
│   on ../../modules/kubernetes-addons/argocd/data.tf line 24, in data "aws_secretsmanager_secret" "ssh_key":
│   24:   for_each = { for k, v in var.applications : k => v if v.ssh_key_secret_name != null }
│ 
│ This object does not have an attribute named "ssh_key_secret_name".
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../../modules/kubernetes-addons/argocd/data.tf line 24, in data "aws_secretsmanager_secret" "ssh_key":
│   24:   for_each = { for k, v in var.applications : k => v if v.ssh_key_secret_name != null }
│ 
│ This object does not have an attribute named "ssh_key_secret_name".
```

But expected no error messages

### Additional Information

This issue appears to be related to PR #201    and the changes it makes to the argocd addon.

**Comment by askulkarni2** [comment]
Thanks for reporting this @ZoesDev. Seems like we need to update the example.
