### ISSUE TITLE
[Bug]: Namespace is hard coded to argocd in all argocd applications

### ISSUE THREAD

**Issue by sarasensible** [aws-samples/aws-eks-accelerator-for-terraform#236]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

v3.2.0

### What is your environment, configuration and the example used?

Terraform version v1.1.4
on darwin_amd64
Used the argocd example with EKS

### What did you do and What did you see instead?

I tried installing the Argo CD apps and ran into the namespace parameter not being honored

This is because the namespace is hard coded to "argocd" in the TF.
https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/1ca8d8de850674caa05162b3cb69153fad5f0815/modules/kubernetes-addons/argocd/main.tf#L88 and in https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/9c38fd09b64b313796dc27b621b7a842d2fdba5b/modules/kubernetes-addons/argocd/argocd-application/templates/application.yaml#L18

**Comment by askulkarni2** [comment]
Thanks for reporting the issue @sarasensible. We will get this fixed.

**Comment by askulkarni2** [comment]
Fixed in https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/283
