### ISSUE TITLE
CSI EFS Driver Add-on

### ISSUE THREAD

**Issue by Filirom1** [aws-samples/aws-eks-accelerator-for-terraform#25]
Hello,

This is a feature request. I tried this repo and note that some AWS components are still missing.
Would it be possible to add [CSI EBS](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html) and [CSI EFS](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) drivers ?

Kind regards
Romain

**Comment by vara-bonthu** [comment]
Hey Romain  @Filirom1  Thanks for raising the FR. We are currently working on a major framework change which should be available as a new release in couple of weeks. I will add the CSI with EBS and EFS to our roadmap. Will keep you posted. Thanks

**Comment by grid-dev** [comment]
@Filirom1 I use v3.2.2 and EBS support is included
