### ISSUE TITLE
[Bug]: It is not possible to define Node Group in tfvars

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/aws-eks-accelerator-for-terraform#250]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

v3.2.2

### What is your environment, configuration and the example used?

I would like to use the `aws-eks-accelerator-for-terraform` module with `managed_node_groups` variable defined "externally" like:

```hcl
# variables.tfvars
managed_node_groups = {
  ng01 = {
    node_group_name = "mgmt01-ng01"

    instance_types = ["t2.small"]
    # subnet_ids = module.aws_vpc.private_subnets   <- This can not be part of "TF variable"
  }
  ng02 = {
    node_group_name = "mgmt01-ng01"

    instance_types = ["t2.small"]
    # subnet_ids = module.aws_vpc.private_subnets   <- This can not be part of "TF variable"
  }
}
```

```hcl
# main.tf
# terraform apply -var-file="variables.tfvars"

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.74.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

variable "managed_node_groups" {
  description = "Map of maps of eks_node_groups to create"
  type        = any
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.11.3"

  name = "test-eks"
  cidr = "10.0.0.0/16"

  azs             = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway      = true
  single_nat_gateway      = true
  enable_dns_hostnames    = true
  map_public_ip_on_launch = true

  public_subnet_tags = {
    "kubernetes.io/cluster/test-eks" = "shared"
    "kubernetes.io/role/elb"         = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/test-eks"  = "shared"
    "kubernetes.io/role/internal-elb" = 1
  }
}

module "aws-eks-accelerator-for-terraform" {
  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform?ref=main"

  tenant      = "mytenant"
  environment = "myenv"
  zone        = "eu-central-1"

  # EKS Cluster VPC and Subnet mandatory config
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  # EKS CONTROL PLANE VARIABLES
  create_eks         = true
  kubernetes_version = "1.21"
  cluster_name       = "test123"

  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = false

  # EKS MANAGED NODE GROUPS
  managed_node_groups = var.managed_node_groups
}
```

But I'm getting the error:

```text
│ Error: Not enough list items
│
│   with module.aws-eks-accelerator-for-terraform.module.aws_eks_managed_node_groups["ng02"].aws_eks_node_group.managed_ng,
│   on .terraform/modules/aws-eks-accelerator-for-terraform/modules/aws-eks-managed-node-groups/main.tf line 5, in resource "aws_eks_node_group" "managed_ng":
│    5:   subnet_ids             = local.managed_node_group["subnet_ids"]
│
│ Attribute requires 1 item minimum, but config has only 0 declared.
```

The `aws-eks-managed-node-groups` module expects `subnet_ids` variable which must be part of the "node_group" definition like it is here: https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-new-vpc/main.tf#L122

Unfortunately Terraform will not allow you to specify `subnet_ids = module.aws_vpc.private_subnets` as part of variable :-(

---

Possible solution may be creating the `eks_managed_node_group_defaults`:

```hcl
eks_managed_node_group_defaults = {
  subnet_ids = module.aws_vpc.private_subnets
}

# managed_node_groups variable doesn't need to have `subnet_ids` definition, because it is already part of the `eks_managed_node_group_defaults`
managed_node_groups = var.managed_node_groups
```

Like it is here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9c9ac81e3a3a91d52b5341d005de80a05a2fa0e8/node_groups.tf#L242

---

Anyway -> The goal is to have possibility to define node_groups as TF variable (tfvars) and not have it "hardcoded" in the module like it is in the examples: https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-new-vpc/main.tf#L117-L124

Thank you...  

### What did you do and What did you see instead?

I can always hardcode the `node_group` definition directly into the module like it is in the examples:

* https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-new-vpc/main.tf#L116-L124

* https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-argocd/main.tf#L145-L153

But this is not a good practice - node groups should be in variables to be easily changed without changing the "main" code...

**Comment by vara-bonthu** [comment]
@ruzickap Thanks for raising the issue 👍🏼 

We will look at the best way to handle the default subnets. Idea is to allow the users to provide correct subnet ids for each managed node group/self managed. For example... one can create one managed node group with private subnets and the other one with public subnets.  We have to accommodate both scenarios

This [locals defaults map](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/modules/aws-eks-managed-node-groups/locals.tf#L9) can have `var.private_subnet_ids` or `var.public_subnet_ids` which we are passing to the node group module already. We may have to introduce `subnet_type ="private/public"` into node groups and then apply relevant subnets as defaults .

Will keep this issue updated

**Comment by ruzickap** [comment]
Make sense to me... 
I'll leave it up to you to decide how to do it.

I just wanted to point out, that currently it is not possible to have "node groups" defined as variables outside the main code...

Thank you.

**Comment by ruzickap** [comment]
Thank you for looking at it and crating PR.

It would be handy to have some example code for the PR.

I tried the code mentioned above and I got the following error:

```text
...
module.aws-eks-accelerator-for-terraform.module.aws_eks.aws_eks_cluster.this[0]: Creating...
╷
│ Error: error creating EKS Cluster (test123): InvalidParameterException: Private and public endpoint access cannot be false
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "f2d1ed14-c24d-4b55-9b29-1d961824b7f4"
│   },
│   ClusterName: "test123",
│   Message_: "Private and public endpoint access cannot be false"
│ }
│
│   with module.aws-eks-accelerator-for-terraform.module.aws_eks.aws_eks_cluster.this[0],
│   on .terraform/modules/aws-eks-accelerator-for-terraform.aws_eks/main.tf line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" {
```

Thank you...
