### ISSUE TITLE
[QUESTION] does this project still use terraform-aws-eks community module ?

### ISSUE THREAD

**Issue by kaykhancheckpoint** [aws-samples/aws-eks-accelerator-for-terraform#252]
#### Please describe your quesiton here

The project mentions in the README.md `This project leverages the community terraform-aws-ek) modules for deploying EKS Clusters.` I can't seem to see anywhere in the modules/ folder reference to this terraform-aws-eks module.

Is it still the case that this project uses https://github.com/terraform-aws-modules/terraform-aws-eks?

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question

**Comment by kaykhancheckpoint** [comment]
Okay because i saw these modules https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/modules/aws-eks-managed-node-groups and i can see that it is not using that community module. 

I was  abit confused what i should use for my prod eks cluster, this repo or the terraform-aws-modules/eks/aws directly.

**Comment by vara-bonthu** [comment]
Closing the issue with the explanation
