### ISSUE TITLE
[FEATURE] Support for terraform-aws-modules v18.0.0+

### ISSUE THREAD

**Issue by agermain** [aws-samples/aws-eks-accelerator-for-terraform#256]
#### Is your feature request related to a problem? Please describe
A race condition fixed as part of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1840

#### Describe the solution you'd like
Support for the upstream v18.0.0 terraform-aws-modules.

#### Describe alternatives you've considered
Considered maintaining our own fork but there's too many breaking changes to keep up. Is there an issue/PR that is already tracking this?

#### Additional context
N/A

**Comment by vara-bonthu** [comment]
Hi @agermain Firstly, Yes It's in our ROADMAP to update the community EKS Cluster module to latest version. 

However, We wont hit this issue with our module as we are only creating the EKS Control Plane using community EKS module. Add-ons are managed by dedicated `kubernetes-addons` sub module. Users can consume this module directly by just passing the EKS cluster id. 

Our [basic example](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-new-vpc/main.tf#L161) shows how to consume this module. e.g., 

`Stage1: Creates EKS Cluster and Node grops`

```hcl
module "aws-eks-accelerator-for-terraform" {
  source = "../.."

  ...
}
```
`Stage2: Creates Add-ons for the existing cluster`

module "kubernetes-addons" {
  source         = "../../modules/kubernetes-addons"
  eks_cluster_id = module.aws-eks-accelerator-for-terraform.eks_cluster_id

  ....
  depends_on = [module.aws-eks-accelerator-for-terraform.managed_node_groups]
}
```
Observe the `depends_on` above which ensures the order when running single TF APPLY. We have written these examples in a single file to allow the users quickly test with minimal instructions.

However, It's a best practise to apply the `Stage1` and `Stage2` using separate Terraform Apply or maintain these in separate TF files with dedicated state file for each.

We are thinking of adding prod ready example using tfvars and separate state for cluster and add-ons soon.

**Comment by agermain** [comment]
Hi @vara-bonthu, thanks for the reply!

The way you've described the example is exactly how we've set it up, except we do it all in one apply. To be more specific, it's actually the coredns addon that is timing out after 15 minutes, if you have seen this happen, do you have any suggestions on avenues to diagnose it?

**Comment by vara-bonthu** [comment]
@agermain Could you please point me to the example that you are trying from this repo? We don't hit this issue with our repo.

You shouldn't get **coredns** add-on issue with our repo as we are not deploying the Add-ons as a part of EKS Cluster creation module. 

```hcl
module "kubernetes-addons" {
  source         = "../../modules/kubernetes-addons"
  eks_cluster_id = module.aws-eks-accelerator-for-terraform.eks_cluster_id

  # EKS Managed Add-ons
  enable_amazon_eks_vpc_cni    = true
  enable_amazon_eks_coredns    = true
  enable_amazon_eks_kube_proxy = true
}
```

Try this [example] (https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/examples/eks-cluster-with-new-vpc/main.tf) and let me know

**Comment by vara-bonthu** [comment]
Closing the issue as this issue is not reproducible with Accelerator module
