### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by skuriyadi** [aws-samples/aws-eks-accelerator-for-terraform#264]
Is anyone facing slowness in applying the plan while using latest version?

Thank you

**Comment by Zvikan** [comment]
Hey @skuriyadi !
Thank you for reporting this issue, we've hearing multiple reports recently and we already merged a fix to improves the terraform plan times, see  https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/257, we've seen TF plan goes down to 30 seconds to 1 minute, compare to 5+ minutes before.

Can you please try using the latest version of `main` branch, and see if terraform plan times is back to normal?
If it's still taking longer than usual, can you please let us know the following:
- Which example you are using ? 
- How long did TF plan take?
- Which code branch/version are you using while testing?

**Comment by skuriyadi** [comment]
Hey @Zvikan ,
I missed the PR https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/257, I upgraded to the latest version and now the planning is taking one minute to build which is expected as I am adding other resources in it. I am seeing below  message but not breaking the plan.

![IMG_9366](https://user-images.githubusercontent.com/56490962/154330245-c7539c96-c231-420c-ade7-b1be9e8bbe53.png)

**Comment by Zvikan** [comment]
@skuriyadi Thank you for the quick reply, happy to read the plan is back to normal.
As for the `module_variable_optional_attrs` - it was added in  https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/223

**Comment by askulkarni2** [comment]
@skuriyadi we use `module_variable_optional_attrs` for [defaults](https://www.terraform.io/language/functions/defaults) so we can use input variables type constraints. 

Looks like the performance issue you reported as been resolved. I will close this for now.
