### ISSUE TITLE
[Bug]: Resource dependency for IAM in terraform destroy

### ISSUE THREAD

**Issue by bonclay7** [aws-samples/aws-eks-accelerator-for-terraform#267]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

v3.2.2

### What is your environment, configuration and the example used?

When deleting example with  

```
cd aws-eks-accelerator-for-terraform/examples/observability/eks-cluster-with-amp-amg-opensearch
terraform destroy -var-file=dev.tfvars
```
 

### What did you do and What did you see instead?

Got an error on 
```
│ Error: error deleting IAM policy arn:aws:iam::xxx:policy/fluentbit-opensearch-access: DeleteConflict: Cannot delete a policy attached to entities.
│       status code: 409, request id: 1e141617-559c-4585-93d6-8e7dad974aeb
│ 
```

**Comment by Zvikan** [comment]
@bonclay7 I wasn't able to reproduce the exact same failure you reported, few questions/notes:
1. Release version 3.2.2 doesn't have the observability example, any chance you ran against `main` branch?
2. Running the example using `main` branch, TF destroy failed with the following error message:
```
│ Error: error waiting for IAM Service Linked Role (arn:aws:iam::<my_account>:role/aws-service-role/es.amazonaws.com/AWSServiceRoleForAmazonElasticsearchService) delete: unexpected state 'FAILED', wanted target 'SUCCEEDED'. last error: %!s(<nil>)
│
│
```

I could also see the error on the IAM console `deletion failed`, I believe a proper dependency (either explicit `depends_on` or implicit) should be added between the linked service and the relevant resources (opensearch mainly) for a cleaner destroy process, as you first must destroy all the linked resources before the IAM role itself.
Shared this with the rest of the team, will create a PR to address this soon.

3. Following to point 2, can you please check if the reported policy (policy/fluentbit-opensearch-access) was added to other IAM roles outside of this TF example?

**Comment by bonclay7** [comment]
Thanks a lot @Zvikan, and yes that was the `main` branch

**Comment by vara-bonthu** [comment]
Closing the issue as fix merged
