### ISSUE TITLE
What is the need of IRSA for ingress-nginx

### ISSUE THREAD

**Issue by gohmc** [aws-samples/aws-eks-accelerator-for-terraform#280]
Hi there,

May I know given this [code](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/4ac674fd9eabc418277ff03fe6ddca8dc24f95ed/modules/kubernetes-addons/ingress-nginx/locals.tf#L57); the ingress-nginx addon module will not create the k8s service account but will create an AWS iam role instead. As a result, the helm deployment failed because the ingress-nginx-controller needs this k8s service account.

How do we create the "ingress-nginx-sa" service account, and may I know why ingress-nginx controller needs IRSA? ingress-nginx does not manipulate AWS resources (eg. ELB) directly.

Thanks.

**Comment by gohmc** [comment]
Thanks, the service account is deployed in the "nginx" namespace rings a bell. May I suggest to make this namespace a variable instead of hardcoded? There are cases where we need multiple ingress-nginx in a cluster, company namespace naming policy etc. Allow to set ingress-nginx namespace will be very helpful.

Tested using the required annotations as you pointed out, the LoadBalancer service request will be handle by the in-tree plug-in which doesn't required ingress-nginx to have IAM permissions. The IRSA assigned to the ingress-nginx-sa in this case could be redundant?

**Comment by kcoleman731** [comment]
@gohmc namespace is configurable via the `ingress_nginx_helm_config` property. Each add-on has a similarly named property that allows you to fully customize the helm deployment. 

https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/examples/advanced/k8s_addons/main.tf#L318

**Comment by askulkarni2** [comment]
>the LoadBalancer service request will be handle by the in-tree plug-in which doesn't required ingress-nginx to have IAM permissions. The IRSA assigned to the ingress-nginx-sa in this case could be redundant?

@wsarwari-amzn can we validate this? If this is true which it sounds like it is, then IRSA is not needed here.

**Comment by wsarwari-amzn** [comment]
I validated it's not using the IRSA to provision or delete AWS resources for NGINX add-on. I'll remove IRSA for NGINX add-on.
