### ISSUE TITLE
Managed node group naming

### ISSUE THREAD

**Issue by tanvp112** [aws-samples/aws-eks-accelerator-for-terraform#290]
I defined a `managed_node_groups` like the following and succeeded provision an EKS cluster:

```
managed_node_groups = {
    t3 = {
      node_group_name = "managed-ondemand"

```

But on the console the name was appended with a long string of data (looks like timestamp):

<img width="314" alt="image" src="https://user-images.githubusercontent.com/57385114/155515030-8aa47390-ade3-4138-9a24-482301cd928f.png">

Can someone help me on what field do I need to set in order not to have the long string appended to the group name?

Thanks!

**Comment by bryantbiggs** [comment]
it is hardcoded so the prefix will always be appended https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/a1e11272fbec39a783a7a4d0641cf6373476b19e/modules/aws-eks-managed-node-groups/main.tf#L3

**Comment by vara-bonthu** [comment]
@tanvp112 Firstly, thanks for raising a question. May i know why you want to keep the static names for Managed Node Groups?  I would like to understand your specific use case.

We don't currently allow the users to use just a static names in our node group module because this is going to cause an issue during the Managed Node group updates.

When Managed Node groups are updated(e.g., change of instance type from m5 to c5), it will create a new replacement node group and delete the old one. So, This is going to cause an issue if you use a `static name for managed node groups`.  because it can’t create a replacement **node group with the same name**.

Hence, we use `node_group_name_prefix` option to managed node groups to avoid the issues related to upgrades.

**Comment by tanvp112** [comment]
@vara-bonthu to my understanding change of instance type is not consider an EKS upgrade. So happen that today I am doing an upgrade for a v1.19:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/57385114/155731193-168414f3-5a83-4346-92aa-74698433c998.png">

to v1.20:

![image](https://user-images.githubusercontent.com/57385114/155731688-317fc7ab-95a3-4ab4-b502-26f6c6d71242.png)

The node group name doesn't need to be changed. It is short and neat, easy to track and use for affinity in the spec. In the event that instance type need changes, we will create a new node group, drain the existing node group and eventually remove the existing node group.  But this is really change of capacity, the control plane, AMI, add-on version do not change.

Are you saying **_aws-eks-accelerator-for-terraform_** actually automate the whole process and that's why it needs to append the long timestamp string? I think it would be great if upgrade and change of node group can be separated.

**Comment by vara-bonthu** [comment]
@tanvp112 
> to my understanding change of instance type is not consider an EKS upgrade. So happen that today I am doing an upgrade for a v1.19

I didn't mention the EKS upgrade. I was talking about updates to the existing Managed Node groups as explained in the example above. It could be a simple change of new `instance type` or a  `release version` or launch template version etc. 

Users doesn't need to go through the multiple steps of `manual process` by adding the code for the new node group, once the TF apply is successful, drain the nodes, update the code repo to delete the old node group, TF apply again to remove the old node groups etc. **where as the same change can be done by just updating the code with new instance type and apply if you use prefix**. 

> Are you saying **_aws-eks-accelerator-for-terraform_** actually automate the whole process and that's why it needs to append the long timestamp string? I think it would be great if upgrade and change instance type can be separated.

Long strings are not appended by our module. Terraform resource provides both `node_group_name` and `node_group_name_prefix`. See the [doc more details](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group). You could only use one of them while creating the node group as one field name conflicts with the other one.  

At this moment we are using only `node_group_name_prefix` to avoid failure for any updates to the existing node groups. Having said that, we can certainly extend this to use `node_group_name` as well if that is something which is helpful for users. 

Hope that helps!

**Comment by tanvp112** [comment]
Thanks, it's clear for me now why the long string and this is the default for **_aws-eks-accelerator-for-terraform_** for the time being. I would certainly suggest to offer `node_group_name` an option over `node_group_name_prefix`.

**Comment by vara-bonthu** [comment]
Thanks @tanvp112 Please feel free to raise a Feature Request. We will add this to our roadmap
