### ISSUE TITLE
[Bug]: Error running 'Getting Started' on govCloud

### ISSUE THREAD

**Issue by camba1** [aws-samples/aws-eks-accelerator-for-terraform#299]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

latest :)  3.4.0

### What is your environment, configuration and the example used?

Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.13.1
+ provider registry.terraform.io/hashicorp/aws v4.3.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### What did you do and What did you see instead?

Tried to follow the ['Getting Started' ](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/getting-started.md) document. I was expecting to get an EKS cluster, instead got the error below:

`creating KMS Key: Malformed policy document Exception`

My guess is that somewhere there is a reference to and arn that has a `arn:aws` prefix which fails because GovCloud uses `arn:aws-us-gov`

Error screenshot:

![Screen Shot 2022-02-28 at 9 55 24 PM](https://user-images.githubusercontent.com/7367366/156269950-30e3ddf1-f302-47a8-886e-a2d9400190c6.png)
.

**Comment by askulkarni2** [comment]
@camba1 thanks for reporting the issue, I've opened a PR with the fix. We will test this and merge it soon.

**Comment by askulkarni2** [comment]
Depends on #345 , #346

**Comment by naris-silpakit** [comment]
Closing this ticket since fixes have been merged.
