### ISSUE TITLE
[Question]: Unable to modify the cluster endpoint security group when enabling private

### ISSUE THREAD

**Issue by jdwilly2001** [aws-samples/aws-eks-accelerator-for-terraform#306]
#### Please describe your quesiton here
I am trying to provision an EKS cluster with this accelerator that is only exposed privately. 

I have enabled the option
cluster_endpoint_private_access = true
and disabled the public access option
cluster_endpoint_public_access = false

The terraform is failing with a timeout while waiting for the cluster to become available. 
Error making request: Get "https://45b44a7f5b411396c1ffa298dd0bb803.gr7.us-east-1.eks.amazonaws.com/healthz": dial tcp 10.66.22.187:443: connect: connection timed out

I can see there is an input for "worker_additional_security_group_ids" but no way to influence the cluster security group which is required to access.

The underlying module https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest exposes some inputs that would allow me to add my private networks into the cluster security group.

#### Provide link to the example related to the quesiton
I am using custom terraform config
```
module "eks_confluent" {
    source = "github.com/aws-samples/aws-eks-accelerator-for-terraform"
    cluster_name = "dataplatform-confluent"
    cluster_endpoint_private_access = true
    cluster_endpoint_public_access = false


    cluster_log_retention_in_days = 7

    enable_irsa = true
    # EKS CLUSTER
    kubernetes_version        = "1.21"
    vpc_id                    = lookup(local.eks_vpc_id, var.target_environment)        # Enter VPC ID
    private_subnet_ids        = lookup(local.eks_subnet_ids, var.target_environment)    # Enter Private Subnet IDs

   # FARGATE PROFILES
   fargate_profiles = {
       default = {
           fargate_profile_name = "fp-default"
           fargate_profile_namespaces = [
               {
                   namespace = "default"
                   k8s_labels = {}
               },
               {
                   namespace = "kube-system"
                   k8s_labels = {}
               }
           ]
           subnet_ids = lookup(local.eks_subnet_ids, var.target_environment)
       }
   }

   map_roles = [
       {
           rolearn = lookup(local.eks_admin_role_arn, var.target_environment)
           username = "admin"
           groups = [
               "system:masters"
           ]
       }
   ]

}
```

#### Additional context
I cannot add rule to the security group since i would need to add the rule before the data.http module runs. I am not sure i can 'inject' my resource into the dependency chain internally to the module

#### More

- [x ] Yes, I have checked the repo for existing issues before raising this question

**Comment by askulkarni2** [comment]
@jdwilly2001 thanks for raising the issue. Just to confirm you are trying access the private endpoint via a connected network and you are trying to add that network to the cluster security group?

**Comment by askulkarni2** [comment]
Great! Thanks for confirming!

**Comment by askulkarni2** [comment]
@jdwilly2001 please this branch a shot https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/bug/306-support-private-endpoint and let us know if that worked for you.

```hcl
module "eks_confluent" {
  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform?ref=bug%2F306-support-private-endpoint"
  cluster_name = "dataplatform-confluent"
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access = false
  cluster_create_endpoint_private_access_sg_rule = true
  cluster_endpoint_private_access_cidrs = ["172.18.0.0/16"]
...
...
```

**Comment by jdwilly2001** [comment]
@askulkarni2 I have implemented this in my repository and is working as expected.
