### ISSUE TITLE
[Bug]: Defining Node Group(s) in tfvars is not working

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/aws-eks-accelerator-for-terraform#332]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

v3.5.0

### What is your environment, configuration and the example used?

I would like to use the `aws-eks-accelerator-for-terraform` module with `managed_node_groups` variable defined "externally" like:

```hcl
# variables.tfvars
managed_node_groups = {
  ng01 = {
    node_group_name = "mgmt01-ng01"
    instance_types = ["t2.small"]
  }
  ng02 = {
    node_group_name = "mgmt01-ng01"
    instance_types = ["t2.small"]
  }
}
```

```hcl
# main.tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.4.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

variable "managed_node_groups" {
  description = "Map of maps of eks_node_groups to create"
  type        = any
}

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.5.0"

  name = "test-eks"
  cidr = "10.0.0.0/16"

  azs             = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

  enable_nat_gateway      = true
  single_nat_gateway      = true
  enable_dns_hostnames    = true
  map_public_ip_on_launch = true

  public_subnet_tags = {
    "kubernetes.io/cluster/test-eks" = "shared"
    "kubernetes.io/role/elb"         = 1
  }

  private_subnet_tags = {
    "kubernetes.io/cluster/test-eks"  = "shared"
    "kubernetes.io/role/internal-elb" = 1
  }
}

module "aws-eks-accelerator-for-terraform" {
  source = "github.com/aws-samples/aws-eks-accelerator-for-terraform?ref=main"

  tenant      = "mytenant"
  environment = "myenv"
  zone        = "eu-central-1"

  # EKS Cluster VPC and Subnet mandatory config
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets

  # EKS CONTROL PLANE VARIABLES
  create_eks         = true
  kubernetes_version = "1.21"
  cluster_name       = "test123"

  cluster_endpoint_private_access = false
  cluster_endpoint_public_access  = false

  # EKS MANAGED NODE GROUPS
  managed_node_groups = var.managed_node_groups
}
```

```bash
$ terraform init
$ terraform apply -var-file="variables.tfvars"
```

But I'm getting the error:

```text
│ Error: error creating EKS Cluster (test123): InvalidParameterException: Private and public endpoint access cannot be false
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "3c2b1b83-a589-481a-94a3-9c074e6ba2f8"
│   },
│   ClusterName: "test123",
│   Message_: "Private and public endpoint access cannot be false"
│ }
│
│   with module.aws-eks-accelerator-for-terraform.module.aws_eks.aws_eks_cluster.this[0],
│   on .terraform/modules/aws-eks-accelerator-for-terraform.aws_eks/main.tf line 11, in resource "aws_eks_cluster" "this":
│   11: resource "aws_eks_cluster" "this" {
```

### What did you do and What did you see instead?

I can always hardcode the `node_group` definition directly into the module like it is in these examples:

* https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-new-vpc/main.tf#L116-L124

* https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/ee7468c52eefa52b5ecfae7a2ffc58b34156550e/examples/eks-cluster-with-argocd/main.tf#L145-L153

But this is not a good practice - node groups should be in variables to be easily changed without changing the "main" code...

**Comment by vara-bonthu** [comment]
@ruzickap I think the error is indicating an issue with `Error: error creating EKS Cluster (test123): InvalidParameterException: Private and public endpoint access cannot be false`

Try the below. Make sure that Terraform client is within the VPC where you are deploying the cluster if you choose the option below

```hcl
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = false
```
or 

This is not recommended but you can access API service publicly. Only for testing

```hcl
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
```

please see this link for more details around the private and public options. 
https://aws.amazon.com/premiumsupport/knowledge-center/eks-public-private-access-api-server/

**Comment by ruzickap** [comment]
You are right... This is not a bug - my bad.

Anyway - using the "external" variable file `variables.tfvars` like it is mentioned above with the `aws-eks-accelerator-for-terraform` module may be handy example...

Do you mind if I will create PR with new example directory `managed-node-groups-tfvars` where I will store + document the example above?

**Comment by kcoleman731** [comment]
Please do @ruzickap. This would be a welcome addition.

**Comment by askulkarni2** [comment]
Closing this. @ruzickap feel free to open create the suggested PR when you get a chance.
