### ISSUE TITLE
[Bug]: Getting started template should not include Fargate

### ISSUE THREAD

**Issue by camba1** [aws-samples/aws-eks-accelerator-for-terraform#345]
### Welcome to Amazon SSP EKS Accelerator!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues) and didn't find any.

### Amazon EKS Accelerator Release version

3.5.0

### What is your environment, configuration and the example used?

Terraform v1.0.10

Using the example from the [getting started](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/getting-started.md) (examples/eks-cluster-with-new-vpc)

### What did you do and What did you see instead?

What I did:
Followed the Getting Started instructions to create a cluster in govCloud. 

What I expected:
Cluster to get created

What happened:
Cluster creation errored out because Fargate is not supported in govCloud

What would you like to see:
Remove the Fargate profile from the Getting Started example  (examples/eks-cluster-with-new-vpc) since Fargate is not available everywhere yet. Removing it will ensure everyone gets a smoother first experience

**Comment by vara-bonthu** [comment]
This has been addressed. fargate profiles removed from this example `examples/eks-cluster-with-new-vpc` . Closing this issue now. Please reopen if you feel if anything is not addressed
