### ISSUE TITLE
Key pair name

### ISSUE THREAD

**Issue by skuriyadi** [aws-samples/aws-eks-accelerator-for-terraform#348]
Hi Team,

How do I add Key pair name in a managed group launch template.

Thank you

**Comment by askulkarni2** [comment]
Hi @skuriyadi, at this time, we do not support `key_name` as input. 

SSM agent however is enabled on the managed node group instances and provides a way for you to access the shell in the managed node group instance.

You should be able to do something like this which you open a shell within your worker node instance.

```sh
export INSTANCE_ID=<instance-id-of-worker-node-instance>
aws ssm start-session --target $INSTANCE_ID
```

It is also possible to setup SSH access over SSM connection, this is described [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html).

Please let us know if the above works for you.

**Comment by skuriyadi** [comment]
I tried to connect using SSM but not getting connected. I am confused about the below step in that:

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html#:~:text=Create%20or%20verify%20that%20you%20have%20a%20Privacy,file%20so%20that%20only%20you%20can%20read%20it.

**Comment by skuriyadi** [comment]
@askulkarni2 can you please check my above comment.

Thank you

**Comment by askulkarni2** [comment]
@skuriyadi the SSH setup you have linked is optional if you want to use an SSH connection. What error you getting if you issue the `aws ssm start-session --target $INSTANCE_ID` command?

**Comment by skuriyadi** [comment]
@askulkarni2 Thank you, I am able to access through Session Manager.
