### ISSUE TITLE
Support Terraform v0.15.0 / v1.0.0

### ISSUE THREAD

**Issue by awsitcloudpro** [aws-samples/aws-eks-accelerator-for-terraform#4]
This repo is currently using Terraform (TF) v0.14.x or lower. It would be nice to use the latest TF version. I ran into a few issues when trying to do that - the terraform apply command errors out. I found that use of Terraform v0.15.0+ requires the following changes:
* Replace TF function map() by [tomap()](https://www.terraform.io/docs/language/functions/map.html).
* Update EKS module vesion to [at least v15.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1317), to replace its internal use of list() by [tolist()](https://www.terraform.io/docs/language/functions/tolist.html).
* Update AWS provider version to [at least v3.37.0](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1340), to support the Warm Pool support added by the EKS module v15.2.0.
* The source folder name can no longer be passed as an argument to the terraform init, plan, and apply commands.

**Comment by vara-bonthu** [comment]
#9 Added new release
