### ISSUE TITLE
"terraform init" fails

### ISSUE THREAD

**Issue by youwalther65** [aws-samples/aws-eks-accelerator-for-terraform#73]
I cloned the repo and tried "terraform init" in various project directories for example:
deploy/eks-cluster-with-new-vpc
aws-eks-accelerator-for-terraform/deploy/advanced/live/preprod/eu-west-1/application_acct/dev

I always get:
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given
│ constraints >= 3.15.0, >= 3.40.0, >= 3.56.0, >= 3.60.0, ~> 3.60.0, >= 3.63.0
╵
I used Terraform v1.0.8 and v1.0.11.

**Comment by askulkarni2** [comment]
Hi @youwalther65, we are not able to reproduce this issue on our end. Would mind running another example such as [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#example-usage) to confirm the issue?

**Comment by youwalther65** [comment]
Thank you. I started a brand new clone and everything works fine. I am going to close the issue.

**Comment by youwalther65** [comment]
Not reproducible
