### ISSUE TITLE
issue with straight steps

### ISSUE THREAD

**Issue by vijoyem** [aws-samples/aws-eks-accelerator-for-terraform#84]
Error: Error fetching Availability Zones: UnauthorizedOperation: You are not authorized to perform this operation.
│       status code: 403, request id: 0a328641-b053-46e7-acdb-53e80a1a3740
│ 
│   with data.aws_availability_zones.available,
│   on main.tf line 35, in data "aws_availability_zones" "available":
│   35: data "aws_availability_zones" "available" {}

**Comment by askulkarni2** [comment]
Hi @vijoyem, this error typically means you do not have adequate permissions to create the cluster. The error directly related to `ec2:DescribeAvailabilityZones` API but there might be others you need permissions to as well. [This](https://github.com/weaveworks/eksctl/blob/main/userdocs/src/usage/minimum-iam-policies.md) is a good list of permissions needed as a reference.
