### ISSUE TITLE
local.argocd_add_on_config.ingressNginx and local.argocd_add_on_config.nginxIngress 

### ISSUE THREAD

**Issue by schwichti** [aws-samples/aws-eks-accelerator-for-terraform#87]
Why there are the keys `ingressNginx` and `nginxIngress`? Looks like a mistake.

https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/3ca142345b00d5546e0c2236b7eb60f862f995b0/locals.tf#L95

https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/3ca142345b00d5546e0c2236b7eb60f862f995b0/locals.tf#L98

**Comment by kcoleman731** [comment]
@schwichti yep and is resolved here. https://github.com/aws-samples/aws-eks-accelerator-for-terraform/pull/83

Thank you!

**Comment by kcoleman731** [comment]
Resolved as of #83
