### ISSUE TITLE
Audit docs and examples for usage of source

### ISSUE THREAD

**Issue by askulkarni2** [aws-samples/aws-eks-accelerator-for-terraform#90]
In all of our readmes, docs and examples we should be pinning the usage of our modules to specific versions.

**Comment by askulkarni2** [comment]
Example https://github.com/aws-samples/terraform-ssp-eks-patterns/blob/056d961ea07678b097224e38371524a6d8c25208/examples/1-eks-cluster-with-new-vpc/main.tf#L98

**Comment by vara-bonthu** [comment]
We can update all the examples with source and version variables once we move this module to Terraform registry. Users can choose any version using the tags

**Comment by prashantbhrgv** [comment]
> We can update all the examples with source and version variables once we move this module to Terraform registry. Users can choose any version using the tags

When are you planning to release the module on terraform registry? Looking forward to it

**Comment by vara-bonthu** [comment]
@prashantbhrgv Thanks for your interest. We are still working on improving the code quality with some refactoring to simplify the user experience. It's going to be soon and will keep you posted

**Comment by kcoleman731** [comment]
Closing issue. Doc improvements are ongoing.
